fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.24.0"
    mysql:
      repo: "https://github.com/puppetlabs/puppetlabs-mysql.git"
      ref: "7.0.0"
    postgresql:
      repo: "https://github.com/puppetlabs/puppetlabs-postgresql.git"
      ref: "5.11.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "4.2.1"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "4.5.1"
    epel:
      repo: "https://github.com/stahnma/puppet-module-epel.git"
      ref: "1.3.0"
    yumrepo:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      puppet_version: ">= 6.0.0"
      ref: "1.0.2"
    augeas:
      repo: "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
      puppet_version: ">= 6.0.0"
      ref: "1.0.3"
  symlinks:
    powerdns: "#{source_dir}"
